routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
    // return view('landing');
});

// Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/users', 'DashboardController@index')->name('users');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index');
Route::get('/superadmin', 'SuperAdminController@index');

// USER RESOURCE
Route::resource('/users', 'UserController');

// DEPARTEMENT RESOURCE
Route::resource('/departements', 'DepartementController');

// ITEM RESOURCE
Route::get('/items/json', 'ItemController@json')->name('items.json');
Route::resource('/items', 'ItemController');
Route::get('/download/{file}', 'ItemController@download');
Route::post('/impor/import_excel', 'ItemController@import_excel');
Route::get('/impor/test', 'ItemController@import_test');
Route::post('/items/{id}/update', 'ItemController@updateItem');
Route::post('/items/store', 'ItemController@storeItem');
Route::post('/items/delete-seleted', 'ItemController@destroySelectedItems');

// CUSTOMER RESOURCE
Route::resource('/customers', 'CustomerController');

// VENDOR RESOURCE
Route::resource('/vendors', 'VendorController');

// PROJECT RESOURCE
Route::get('/projects/{id}/add-item/{project_id}/{qty}', 'ProjectController@addItem')->name('projects.additem');
Route::get('/projects/json/{id_project}', 'ProjectController@json')->name('projects.json');
Route::delete('/projects/item/{id}', 'ProjectController@destroy_item')->name('projects.deleteitem');

Route::get('/projects/{id}/items', 'ProjectController@items');
Route::resource('/projects', 'ProjectController');

// PURCHASE REQUISITION RESOURCE
Route::get('/purchase-requisitions/{id}/create', 'PurchaseRequisitionController@create_pr');
Route::get('/purchase-requisitions/{id}/approve', 'PurchaseRequisitionController@approve');
Route::get('/purchase-requisitions/{id}/cancel', 'PurchaseRequisitionController@cancel');
Route::get('/purchase-requisitions/{id}/items', 'PurchaseRequisitionController@items');
Route::delete('/purchase-requisitions/{id}/item', 'PurchaseRequisitionController@destroyItem')->name('projects.deleteItem');
Route::post('/purchase-requisitions/{pr_id}/add-item', 'PurchaseRequisitionController@addItem');
Route::post('/purchase-requisitions/update-item', 'PurchaseRequisitionController@updateItem');

Route::resource('/purchase-requisitions', 'PurchaseRequisitionController');

// PURCHASE ORDER RESOURCE
Route::get('/purchase-orders/{id}/list', 'PurchaseOrderController@list');
Route::get('/purchase-orders/{id}/items', 'PurchaseOrderController@items');
Route::get('/purchase-orders/{id}/create/{pr}', 'PurchaseOrderController@create_po');
Route::post('/purchase-orders/{po_id}/add-item', 'PurchaseOrderController@addItem');
Route::post('/purchase-orders/update-item', 'PurchaseOrderController@updateItem');
Route::delete('/purchase-orders/{id}/item', 'PurchaseOrderController@destroyItem');

Route::post('/purchase-orders/update-po', 'PurchaseOrderController@updatePO');
Route::post('/purchase-orders/update-status', 'PurchaseOrderController@updateStatus');

Route::resource('/purchase-orders', 'PurchaseOrderController');

// WAREHOUSE SUMMARY
Route::resource('/warehouse/summary', 'WarehouseSummaryController');
Route::get('/warehouse/purchase-orders/{id}/items', 'WarehouseSummaryController@po');
Route::get('/warehouse/trending', 'WarehouseSummaryController@trending');
Route::post('/warehouse/purchase-orders/{id}/verified', 'WarehouseSummaryController@verified');

// WAREHOUSE ITEM
Route::get('/warehouse/items-in', 'WarehouseItemController@itemIn');
Route::get('/warehouse/items-out', 'WarehouseItemController@itemOut');
Route::resource('/warehouse/items', 'WarehouseItemController');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'departement_id', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // public function departement()
    // {
    //     return $this->hasMany('App\Departement');
    // }

    public function departement()
    {
        return $this->belongsTo('App\Departement');
    }

    public function roles()
    {
        return $this
            ->belongsToMany('App\Role', 'role_user')
            ->withTimestamps();
    }

    public function getRoles()
    {
        return $this->roles()->where('names', 'ROLE_ADMIN')->first();

    }

    public function hasPrivilege($privilege)
    {
        // Auth::logout();
        // dd(Auth::guard('web')->user()->departement);

        if ($this->departement()->count() > 0) {
            $id = $this->departement()->first()->id;
            $cekPrivilege = app('App\Departement')::findOrFail($id)->privileges()->where('name', $privilege)->get();
            if ($cekPrivilege->count()) {
                return true;
            } else {
                return false;
            }
        } else {
            // Cek jika departement tidak terdaftar
            return 403;
        }

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Departement as Departements;
use App\User as Users;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('privilege:UsersView', ['only' => 'index']);
        $this->middleware('privilege:UsersCreate', ['only' => 'create']);
        $this->middleware('privilege:UsersEdit', ['only' => 'edit']);
        // $this->middleware('privilege:DepartementsEdit', ['only' => ]);
        $this->middleware('privilege:UsersDelete', ['only' => 'destroy']);
    }

    public function index()
    {
        //

        $data['page_title'] = 'Users Management';
        $data['users'] = Users::orderBy('id', 'desc')->get();
        return view('user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['page_title'] = 'Create User';
        $data['departements'] = Departements::all();
        return view('user.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:4', 'confirmed'],
            'departement_id' => ['required'],
            'avatar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if ($request->hasFile('avatar')) {
            $image = $request->file('avatar');
            $name = time() . '.' . $image->getClientOriginalExtension();
            $destinationPath = public_path('backend/images/users');
            $image->move($destinationPath, $name);
            $data['avatar'] = $name;
        }

        $data['name'] = $request->input('name');
        $data['email'] = $request->input('email');
        $data['password'] = bcrypt($request->input('password'));
        $data['departement_id'] = $request->input('departement_id');

        Users::create($data);

        return redirect('users')->with(['create' => 'Data saved successfully!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['page_title'] = 'Edit User';
        $data['departements'] = Departements::all();
        $data['user'] = Users::findOrFail($id);
        // dd($departement);
        return view('user.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data_user = Users::findOrFail($id);

        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $id],
            'departement_id' => ['required'],
        ]);

        if ($request->input('password')) {
            $request->validate([
                'password' => ['string', 'min:5'],
            ]);
            $data['password'] = bcrypt($request->input('password'));
        }

        if ($request->hasFile('avatar')) {
            // Check Image
            $request->validate([
                'avatar' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            ]);

            // Delete Img
            if ($data_user->avatar) {
                $image_path = public_path('backend/images/users/' . $data_user->avatar); // Value is not URL but directory file path
                if (File::exists($image_path)) {
                    File::delete($image_path);
                }
            }

            $image = $request->file('avatar');
            $name = time() . '.' . $image->getClientOriginalExtension();
            $destinationPath = public_path('backend/images/users');
            $image->move($destinationPath, $name);
            $data['avatar'] = $name;
        }

        $data['name'] = $request->input('name');
        $data['email'] = $request->input('email');
        $data['departement_id'] = $request->input('departement_id');

        // dd($data);
        Users::where('id', $id)->update($data);

        return redirect('users')->with(['update' => 'Data updated successfully!']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::transaction(function () use ($id) {
            $data_user = Users::findOrFail($id);
            // Delete Img
            if ($data_user->avatar) {
                $image_path = public_path('backend/images/users/' . $data_user->avatar); // Value is not URL but directory file path
                if (File::exists($image_path)) {
                    File::delete($image_path);
                }
            }
            Users::where('id', $id)->delete();
        });

        // redirect('departements')->with(['delete' => 'Data deleted successfully!']);
        Session::flash('delete', 'Data deleted successfully!');
        return response()->json(['status' => '200']);
    }
}

resources/views/user/create.blade.php
@extends('layouts.main')

@section('page_title',$page_title)

@section('css')
<style>
    .select2-results__option[aria-selected=true] {
        display: none;
    }

</style>

@endsection

@section('content')
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div w>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-6 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18">{{$page_title}}</span>
                        {{-- <a href="{{url('departements/create')}}"> <button
                            class="btn btn-sm btn-danger float-right"><i class="icon ion ion-ios-plus-outline"></i>
                            New
                            Data</button>
                        </a> --}}
                        <hr>
                        <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                            @csrf
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <div class="form-group ">
                                <label for="">Full Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" type="text"
                                    name="name" placeholder="input user name" value="{{old('name')}}">
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                                @endif
                            </div>
                            <div class="form-group ">
                                <label for="">Email</label>
                                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" type="email"
                                    name="email" placeholder="input user email" value="{{old('email')}}">
                                @if ($errors->has('email'))
                                <small class="text-danger">{{ $errors->first('email') }}</small>
                                @endif
                            </div>

                            <div class="form-group ">
                                <label for="password" class=" ">{{ __('Password') }}</label>
                                <input id="password" type="password"
                                    class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                    name="password" placeholder="input password" >

                                @if ($errors->has('password'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                @endif
                            </div>

                            <div class="form-group ">
                                <label for="password-confirm">{{ __('Confirm Password') }}</label>
                                <input id="password-confirm" type="password" class="form-control"
                                        name="password_confirmation" placeholder="same with password" s>
                            </div>



                            <div class="form-group   {{ $errors->has('departement_id') ? ' has-danger' : '' }}">
                                <label for="">Departement</label>
                                <br>
                                <select class="form-control select2 " name="departement_id"
                                    data-placeholder="Choose one  ">
                                    <option label="Choose one"></option>
                                    @foreach ($departements as $departement)
                                    <option value="{{$departement->id}}"
                                        @if (old('departement_id') == $departement->id)
                                            {{ 'selected=selected'}}
                                        @endif
                                        >{{$departement->name}}</option>

                                    @endforeach
                                </select>
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('departement_id') }}</small>
                                @endif
                            </div>

                            <div class="form-group ">
                                <label for="">Avatar</label>
                                <input class="form-control{{ $errors->has('avatar') ? ' is-invalid' : '' }}"  type="file"
                                    name="avatar"   value="{{old('avatar')}}">
                                @if ($errors->has('avatar'))
                                    <small class="text-danger">{{ $errors->first('avatar') }}</small>
                                @endif
                            </div>

                            <div class="form-group">
                                <button class="btn   btn-success" type="submit"><i class="far fa-save"></i>
                                    Save</button>
                                <a href="{{ url('users') }}"><button class="btn   btn-danger" type="button"><i
                                            class="far fa-arrow-alt-circle-left"></i> Cancel</button></a>

                            </div>
                        </form>
                    </div>
                    <hr>

                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->
@endsection

resources/views/user/edit.blade.php
@extends('layouts.main')

@section('page_title',$page_title)

@section('css')
<style>
    .select2-results__option[aria-selected=true] {
        display: none;
    }

</style>

@endsection

@section('content')
<script type="text/javascript">
    function makeItPassword() {
        document.getElementById("passcontainer")
            .innerHTML = "<input class=\"form-control\" id=\"password\" name=\"password\" type=\"password\"/>";
        document.getElementById("password").focus();
    }

</script>
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div w>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-6 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18">{{$page_title}}</span>
                        {{-- <a href="{{url('departements/create')}}"> <button
                            class="btn btn-sm btn-danger float-right"><i class="icon ion ion-ios-plus-outline"></i>
                            New
                            Data</button>
                        </a> --}}
                        <hr>
                        <form method="POST" action="{{ route('users.update', $user->id) }}" enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <div class="form-group ">
                                <label for="">Full Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" type="text"
                                    name="name" placeholder="input user name" value="{{$user->name}}">
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                                @endif
                            </div>
                            <div class="form-group ">
                                <label for="">Email</label>
                                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" type="email"
                                    name="email" placeholder="input user email" value="{{$user->email}}">
                                @if ($errors->has('email'))
                                <small class="text-danger">{{ $errors->first('email') }}</small>
                                @endif
                            </div>

                            <div class="form-group ">
                                <label for="password" class=" ">{{ __('Password') }}</label>
                                <span id="passcontainer">
                                    <input  id="password" type="password"
                                    class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}"
                                    name="password" value="" placeholder="">
                                </span>
                                <small>(Don't fill in if it's not changed)</small>

                                @if ($errors->has('password'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                @endif
                            </div>




                            <div class="form-group   {{ $errors->has('departement_id') ? ' has-danger' : '' }}">
                                <label for="">Departement</label>
                                <br>
                                <select class="form-control select2 " name="departement_id"
                                    data-placeholder="Choose one  ">
                                    <option label="Choose one"></option>
                                    @foreach ($departements as $departement)
                                    <option value="{{$departement->id}}" @if ($user->departement_id == $departement->id)
                                        {{ 'selected=selected'}}
                                        @endif
                                        >{{$departement->name}}</option>

                                    @endforeach
                                </select>
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('privileges') }}</small>
                                @endif
                            </div>

                            <div class="form-group ">
                                <label for="">Avatar</label>
                                <br>
                                <img height="100" class="mg-b-10" src="{{url('backend/images/users/'.$user->avatar)}}" alt="">
                                <br>

                                <input class="form-control{{ $errors->has('avatar') ? ' is-invalid' : '' }}" type="file"
                                    name="avatar" value="{{old('avatar')}}">
                                @if ($errors->has('avatar'))
                                <small class="text-danger">{{ $errors->first('avatar') }}</small>
                                @endif
                            </div>

                            <div class="form-group">
                                <button class="btn   btn-success" type="submit"><i class="far fa-save"></i>
                                    Save</button>
                                <a href="{{ url('users') }}"><button class="btn   btn-danger" type="button"><i
                                            class="far fa-arrow-alt-circle-left"></i> Cancel</button></a>

                            </div>
                        </form>
                    </div>
                    <hr>

                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->
@endsection

resources/views/user/index.blade.php
@extends('layouts.main')

@section('page_title',$page_title)


@section('content')
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-12 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18"><i class="icon ion ion-ios-people tx-22"></i> {{$page_title}}</span>
                        <a href="{{url('users/create') }}">
                            <button class="btn btn-sm btn-info float-right"><i
                                    class="icon ion ion-ios-plus-outline"></i>
                                New
                                Data</button>
                        </a>
                    </div>
                    <hr>
                    @if(session()->has('create'))
                    <div class="alert alert-success wd-50p">
                        {{ session()->get('create') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    @if(session()->has('update'))
                    <div class="alert alert-warning wd-50p">
                        {{ session()->get('update') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>
                    @endif


                    @if(session()->has('delete'))
                    <div class="alert alert-danger wd-50p">
                        {{ session()->get('delete') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>
                    @endif
                    <div class="table-wrapper ">
                        <table class="table display responsive nowrap" id="datatable1">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Avatar</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Departement</th>
                                    <th width="15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                $no=1;
                                @endphp
                                @foreach ($users as $user)


                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>
                                        @if ($user->avatar)
                                        <img class="wd-32 rounded-circle img-profile" src="{{asset('backend/images/users/'.$user->avatar)}}" alt="profile">
                                        @else
                                        <img class="wd-32 rounded-circle img-profile" src="https://www.ommel.fi/content/uploads/2019/03/dummy-profile-image-male.jpg" alt="profile">
                                        @endif
                                        </td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        {{--                                         
                                    @php
                                        dd($user->departement->first())
                                        
                                    @endphp
                                    @foreach ($user->departement->first() as $departement)
                                    {!! '<span class="badge badge-info">'.$departement->name .'</span>' !!}

                                    @endforeach --}}
                                        {{$user->departement['name']}}
                                    </td>
                                    <td>
                                       
                                        <a href="{{url('users/'.$user->id.'/edit/') }}">
                                            <button class="btn btn-warning btn-sm text-white">
                                                <i class="icon icon ion ion-edit"></i> Edit

                                            </button>
                                        </a>
                                        @if (Auth::user()->id != $user->id)
                                            <button class="btn btn-danger btn-sm text-white"
                                                onclick="deleteData({{$user->id}})">
                                                <i class="icon icon ion ion-ios-trash-outline"></i> Delete
                                            </button>
                                        @endif
                                        
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                    {{-- {{ $users->link    s() }} --}}
                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->
@endsection

@push('scripts')
    <script>
    var route_url= 'users'; 
    </script>
@endpush