routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/login');
    // return view('landing');
});

// Dashboard
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
Route::get('/users', 'DashboardController@index')->name('users');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@index');
Route::get('/superadmin', 'SuperAdminController@index');

// USER RESOURCE
Route::resource('/users', 'UserController');

// DEPARTEMENT RESOURCE
Route::resource('/departements', 'DepartementController');

// ITEM RESOURCE
Route::get('/items/json', 'ItemController@json')->name('items.json');
Route::resource('/items', 'ItemController');
Route::get('/download/{file}', 'ItemController@download');
Route::post('/impor/import_excel', 'ItemController@import_excel');
Route::get('/impor/test', 'ItemController@import_test');
Route::post('/items/{id}/update', 'ItemController@updateItem');
Route::post('/items/store', 'ItemController@storeItem');
Route::post('/items/delete-seleted', 'ItemController@destroySelectedItems');

// CUSTOMER RESOURCE
Route::resource('/customers', 'CustomerController');

// VENDOR RESOURCE
Route::resource('/vendors', 'VendorController');

// PROJECT RESOURCE
Route::get('/projects/{id}/add-item/{project_id}/{qty}', 'ProjectController@addItem')->name('projects.additem');
Route::get('/projects/json/{id_project}', 'ProjectController@json')->name('projects.json');
Route::delete('/projects/item/{id}', 'ProjectController@destroy_item')->name('projects.deleteitem');

Route::get('/projects/{id}/items', 'ProjectController@items');
Route::resource('/projects', 'ProjectController');

// PURCHASE REQUISITION RESOURCE
Route::get('/purchase-requisitions/{id}/create', 'PurchaseRequisitionController@create_pr');
Route::get('/purchase-requisitions/{id}/approve', 'PurchaseRequisitionController@approve');
Route::get('/purchase-requisitions/{id}/cancel', 'PurchaseRequisitionController@cancel');
Route::get('/purchase-requisitions/{id}/items', 'PurchaseRequisitionController@items');
Route::delete('/purchase-requisitions/{id}/item', 'PurchaseRequisitionController@destroyItem')->name('projects.deleteItem');
Route::post('/purchase-requisitions/{pr_id}/add-item', 'PurchaseRequisitionController@addItem');
Route::post('/purchase-requisitions/update-item', 'PurchaseRequisitionController@updateItem');

Route::resource('/purchase-requisitions', 'PurchaseRequisitionController');

// PURCHASE ORDER RESOURCE
Route::get('/purchase-orders/{id}/list', 'PurchaseOrderController@list');
Route::get('/purchase-orders/{id}/items', 'PurchaseOrderController@items');
Route::get('/purchase-orders/{id}/create/{pr}', 'PurchaseOrderController@create_po');
Route::post('/purchase-orders/{po_id}/add-item', 'PurchaseOrderController@addItem');
Route::post('/purchase-orders/update-item', 'PurchaseOrderController@updateItem');
Route::delete('/purchase-orders/{id}/item', 'PurchaseOrderController@destroyItem');

Route::post('/purchase-orders/update-po', 'PurchaseOrderController@updatePO');
Route::post('/purchase-orders/update-status', 'PurchaseOrderController@updateStatus');

Route::resource('/purchase-orders', 'PurchaseOrderController');

// WAREHOUSE SUMMARY
Route::resource('/warehouse/summary', 'WarehouseSummaryController');
Route::get('/warehouse/purchase-orders/{id}/items', 'WarehouseSummaryController@po');
Route::get('/warehouse/trending', 'WarehouseSummaryController@trending');
Route::post('/warehouse/purchase-orders/{id}/verified', 'WarehouseSummaryController@verified');

// WAREHOUSE ITEM
Route::get('/warehouse/items-in', 'WarehouseItemController@itemIn');
Route::get('/warehouse/items-out', 'WarehouseItemController@itemOut');
Route::resource('/warehouse/items', 'WarehouseItemController');

app/Departement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departement extends Model
{
    public $timestamps = true;

    public function privileges()
    {
        return $this
            ->belongsToMany('App\Privilege')
            ->withTimestamps();
    }

    public function privilege($id)
    {
        return $this->privileges()->where('departement_id', $id)->orderBy('name', 'asc');
    }

    public function users()
    {
        return $this->hasMany('App\User');
    }

    protected $fillable = [
        'name', 'description',
    ];

}

app/Http/Controllers/DepartementController.php
<?php

namespace App\Http\Controllers;

use App\Departement as Departements;
use App\DepartementPrivilege as DepartementPrivileges;
use App\Privilege as Privileges;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Session;

class DepartementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('privilege:DepartementsView', ['only' => 'index']);
        $this->middleware('privilege:DepartementsCreate', ['only' => 'create']);
        $this->middleware('privilege:DepartementsEdit', ['only' => 'edit']);
        // $this->middleware('privilege:DepartementsEdit', ['only' => ]);
        $this->middleware('privilege:DepartementsDelete', ['only' => 'destroy']);
    }

    public function index()
    {

        $data['page_title'] = ' Departements Management';
        $data['departements'] = Departements::paginate(10);

        return view('departement.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['page_title'] = 'Create Departement';
        $data['departements'] = Departements::all();
        $data['privileges'] = Privileges::all();

        return view('departement.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data['name'] = $request->input('name');
        $data['description'] = $request->input('description');
        $data['privileges'] = $request->input('privileges');

        $request->validate([
            'name' => 'required|min:2',
            'privileges' => 'required',
        ]);

        DB::transaction(function () use ($data) {
            // Insert Data Departement
            $departement = Departements::create($data);

            // Insert To departement_privileges
            $data_departement_privilege = array();

            for ($i = 0; $i < count($data['privileges']); $i++) {
                $data_push = array(
                    'privilege_id' => $data['privileges'][$i],
                    'departement_id' => $departement['id'],
                );
                array_push($data_departement_privilege, $data_push);
            }

            DepartementPrivileges::insert($data_departement_privilege);
        });
        return redirect('departements')->with(['create' => 'Data saved successfully!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['departement'] = Departements::findOrFail($id);

        $data['privileges'] = $data['departement']->privilege($id)->get();
        return view('departement.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['page_title'] = 'Edit Departement';
        $data['privileges'] = Privileges::all();
        $data['departement'] = Departements::findOrFail($id);
        // dd($departement);
        return view('departement.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data['name'] = $request->input('name');
        $data['description'] = $request->input('description');
        $privileges = $request->input('privileges');

        $request->validate([
            'name' => 'required|min:2',
            'privileges' => 'required',
        ]);

        DB::transaction(function () use ($data, $id, $privileges) {

            // Update departememnt and Remove All Departement Privilege
            $departement = Departements::where('id', $id)->update($data);
            $departement = DepartementPrivileges::where('departement_id', $id)->delete();

            $data_departement_privilege = array();
            for ($i = 0; $i < count($privileges); $i++) {
                $data_push = array(
                    'privilege_id' => $privileges[$i],
                    'departement_id' => $id,
                );
                array_push($data_departement_privilege, $data_push);
            }

            DepartementPrivileges::insert($data_departement_privilege);
        });
        return redirect('departements')->with(['update' => 'Data updated successfully!']);

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::transaction(function () use ($id) {
            $departement = Departements::where('id', $id)->delete();
            $departement_privilege = DepartementPrivileges::where('departement_id', $id)->delete();
        });

        // redirect('departements')->with(['delete' => 'Data deleted successfully!']);
        Session::flash('delete', 'Data deleted successfully!');
        return response()->json(['status' => '200']);

    }
}

resources/views/departement/create.blade.php
@extends('layouts.main')

@section('page_title',$page_title)

@section('css')
<style>
    .select2-results__option[aria-selected=true] {
        display: none;
    }

</style>

@endsection

@section('content')
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div w>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-6 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18">{{$page_title}}</span>
                        {{-- <a href="{{url('departements/create')}}"> <button
                            class="btn btn-sm btn-danger float-right"><i class="icon ion ion-ios-plus-outline"></i>
                            New
                            Data</button>
                        </a> --}}
                        <hr>
                        <form method="POST" action="{{ route('departements.store') }}">
                            @csrf
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="form-group ">
                                <label for="">Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" type="text" name="name"
                            placeholder="input departement name" value="{{old('name')}}">
                                @if ($errors->has('name'))
                                    <small class="text-danger">{{ $errors->first('name') }}</small>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">Description <small>(Optional</small>)</label>
                                <textarea name="description" class="form-control" id="" cols="30" rows="3">{{old('description')}}</textarea>
                            </div>

                            <div class="form-group has-danger {{ $errors->has('privileges') ? ' has-danger' : '' }}">
                                <label for="">Privileges</label>
                                <br>
                                <small>Select All</small>
                                <input type="checkbox" id="checkbox">
                                <select class="form-control select2 " name="privileges[]" id="e1"
                                    data-placeholder="Choose one (with optgroup)" multiple>
                                    {{-- <option label="Choose one"></option> --}}
                                    @foreach ($privileges as $privilege)
                                    <option value="{{$privilege->id}}" 
                                    @if (old('privileges') == $privilege->id)
                                        {{ 'selected:selected' }}
                                    @endif
                                    >
                                    
                                    {{$privilege->name}}</option>

                                    @endforeach
                                </select>
                                @if ($errors->has('name'))
                                    <small class="text-danger">{{ $errors->first('privileges') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <button class="btn   btn-success" type="submit"><i class="far fa-save"></i>
                                    Save</button>
                                <a href="{{ url('departements') }}"><button class="btn   btn-danger" type="button"><i
                                            class="far fa-arrow-alt-circle-left"></i> Cancel</button></a>

                            </div>
                        </form>
                    </div>
                    <hr>

                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->
@endsection


@push('scripts')
<script>
    $("#e1").select2();
    $("#checkbox").click(function () {
        if ($("#checkbox").is(':checked')) {
            $("#e1 > option").prop("selected", "selected");
            $("#e1").trigger("change");
        } else {
            $("#e1 > option").removeAttr("selected");
            $("#e1").val("");
            $("#e1").trigger("change");
        }
    });

    $("#button").click(function () {
        alert($("#e1").val());
    });

    $("select").on("select2:select", function (evt) {
        var element = evt.params.data.element;
        var $element = $(element);
        $element.detach();
        $(this).append($element);
        $(this).trigger("change");
    });

    
    
</script>

    @if (old('privileges'))
        <script>
        $("#e1").val([
                @foreach (old('privileges') as $privilege_selected)
                    {!! $privilege_selected !!},  
                @endforeach 
        ]);
        </script>
    @endif
@endpush

resources/views/departement/edit.blade.php
@extends('layouts.main')

@section('page_title',$page_title)

@section('css')
<style>
    .select2-results__option[aria-selected=true] {
        display: none;
    }

</style>

@endsection

@section('content')
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div w>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-6 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18">{{$page_title}}</span>
                        {{-- <a href="{{url('departements/create')}}"> <button
                            class="btn btn-sm btn-danger float-right"><i class="icon ion ion-ios-plus-outline"></i>
                            New
                            Data</button>
                        </a> --}}
                        <hr>
                        <form method="POST" action="{{ route('departements.update', $departement->id) }}">
                            @csrf
                            <input type="hidden" name="_method" value="PATCH">
                            @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                            @endif
                            <div class="form-group ">
                                <label for="">Name</label>
                                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" type="text"
                                    name="name" placeholder="input departement name" value="{{ $departement->name }}" >
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('name') }}</small>
                                @endif
                            </div>

                            <div class="form-group">
                                <label for="">Description <small>(Optional</small>)</label>
                                <textarea name="description" class="form-control" id="" cols="30"
                                    rows="3">{{ $departement->description }}</textarea>
                            </div>

                            <div class="form-group has-danger {{ $errors->has('privileges') ? ' has-danger' : '' }}">
                                <label for="">Privileges</label>
                                <br>
                                <small>Select All</small>
                                <input type="checkbox" id="checkbox">
                                <select class="form-control select2 " name="privileges[]" id="e1"
                                    data-placeholder="Choose one (with optgroup)" multiple>
                                    {{-- <option label="Choose one"></option> --}}
                                    @foreach ($privileges as $privilege)
                                        
                                        <option value="{{$privilege->id}}"  >{{$privilege->name}}</option>

                                    @endforeach
                                </select>
                                @if ($errors->has('name'))
                                <small class="text-danger">{{ $errors->first('privileges') }}</small>
                                @endif
                            </div>
                            <div class="form-group">
                                <button class="btn   btn-success" type="submit"><i class="far fa-save"></i>
                                    Save</button>
                                <a href="{{ url('departements') }}"><button class="btn   btn-danger" type="button"><i
                                            class="far fa-arrow-alt-circle-left"></i> Cancel</button></a>

                            </div>
                        </form>
                    </div>
                    <hr>

                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->
@endsection


@push('scripts')
<script>
    $("#e1").select2();
    $("#checkbox").click(function () {
        if ($("#checkbox").is(':checked')) {
            $("#e1 > option").prop("selected", "selected");
            $("#e1").trigger("change");
        } else {
            $("#e1 > option").removeAttr("selected");
            $("#e1").val("");
            $("#e1").trigger("change");
        }
    });

    $("#button").click(function () {
        alert($("#e1").val());
    });

    $("select").on("select2:select", function (evt) {
        var element = evt.params.data.element;
        var $element = $(element);
        $element.detach();
        $(this).append($element);
        $(this).trigger("change");
    });


    // SET VALUE SELECT 2
    $("#e1").val([

        @foreach ($departement->privileges->all() as $privilege_selected)
            {{$privilege_selected->id.',' }}             
        @endforeach 
    ]);
</script>
@endpush

resources/views/departement/index.blade.php
@extends('layouts.main')

@section('page_title',$page_title)


@section('content')
<div class="br-mainpanel">
    <div class="br-pageheader">
        <div>
            <nav class="breadcrumb pd-0 mg-0 tx-12">
                <a class="breadcrumb-item" href="index.html">{{config('app.name')}}</a>
                <span class="breadcrumb-item active">{{$page_title}}</span>

            </nav>

        </div>
    </div><!-- br-pageheader -->


    <div class="br-pagebody">

        <div class="row">

            <div class="col-lg-8 mg-b-20">
                <div class="br-section-wrapper" style="padding: 30px 20px">
                    <div style="align">
                        <span class="tx-bold tx-18"><i class="icon ion ion-ios-people tx-22"></i> {{$page_title}}</span>
                        <a href="{{url('departements/create') }}">
                            <button class="btn btn-sm btn-info float-right"><i
                                    class="icon ion ion-ios-plus-outline"></i>
                                New
                                Data</button>
                        </a>
                    </div>
                    <hr>
                    @if(session()->has('create'))
                    <div class="alert alert-success wd-50p">
                        {{ session()->get('create') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    @if(session()->has('update'))
                    <div class="alert alert-warning wd-50p">
                        {{ session()->get('update') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>
                    @endif


                    @if(session()->has('delete'))
                    <div class="alert alert-danger wd-50p">
                        {{ session()->get('delete') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>

                    </div>
                    @endif
                    <div class="table-wrapper ">
                        <table class="table display responsive nowrap" id="datatable1">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Privilege</th>
                                    <th width="15%">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php
                                $no=1;
                                @endphp
                                @foreach ($departements as $departement)


                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $departement->name }}</td>
                                    <td>
                                        <button onclick="detailPrivileges({{$departement->id}})" class="btn btn-info btn-sm"><i class="ion ion-eye"></i> View
                                            Privileges</button>
                                    </td>

                                    <td>
                                        <a href="{{url('departements/'.$departement->id.'/edit/') }}">
                                            <button class="btn btn-warning btn-sm text-white">
                                                <i class="icon icon ion ion-edit"></i> Edit

                                            </button>
                                        </a>
                                        <button class="btn btn-danger btn-sm text-white"
                                            onclick="deleteData({{$departement->id}})">
                                            <i class="icon icon ion ion-ios-trash-outline"></i> Delete
                                        </button>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                    {{-- {{ $users->link    s() }} --}}
                </div>

            </div>

        </div>

    </div><!-- br-pagebody -->

    @include('layouts.partials.footer')
</div><!-- br-mainpanel -->\

<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>
@endsection

@push('scripts')
<script>
    
    var route_url= 'departements'; 
  
    function detailPrivileges(id) {
        $.confirm({
            title: 'Detail Privilege',
            theme : 'material',
            backgroundDismiss: true, // this will just close the modal
            content: 'url:departements/'+id,
            onContentReady: function () {
                var self = this;
                // this.setContentPrepend('<div>Prepended text</div>');
                // setTimeout(function () {
                //     self.setContentAppend('<div>Appended text after 2 seconds</div>');
                // }, 2000);
            },
            columnClass: 'medium',
        });
    }

</script>
@endpush

resources/views/departement/show.blade.php
 
    <table class="table display responsive nowrap datatable2 table-bordered" id=""> 
        <thead class="thead-dark">
            <th width="2%">No</th>
            <th>Privilege</th>
        </thead>
        <tbody>
            @php
                $no = 1;
            @endphp
            @foreach ($privileges as $item)
                <tr>
                <td>{{$no++}}</td>
                    <td>{{$item->name}}</td>
                </tr>
            @endforeach

            
            
        </tbody>
    </table>
     